main: Loup_Garou_1_15_2.Main
name: LoupGarou
version: 1.0
api-version: 1.13
author: Mwa
description: Loup Garou du Q

commands:
  lgGame:
    aliases: [loupGarouGame]
    usage: "Usage: /<command> [create|delete|join|leave|list]"
    description: all lg game interactions
  lgSetup:
    aliases: [loupGarouSetup]
    usage: "Usage: /<command> [addHouse|housesList|setExecutionRoom]"
    description: all setup interactions